const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const sandbox={};sandbox.window=sandbox;vm.createContext(sandbox);
for(const file of ['workout-tracking.js','progress-data.js'])vm.runInContext(fs.readFileSync('dist/'+file,'utf8'),sandbox);
const progress=sandbox.GymProgressData;
const catalog={curl:{id:'curl',name:'Dumbbell Curl',group:'Biceps'},other:{id:'other',name:'Hammer Curl',group:'Biceps'},assisted:{id:'assisted',name:'Machine Assisted Pull-Up',equipment:'Machine',group:'Back'}};
const lookup=record=>catalog[record.id]||{id:record.id,name:record.name,group:record.group||'Activity'};
const lift=(weight,extra={})=>({id:'curl',done:true,tracking:'reps',sets:3,reps:10,weight,weightUnit:'kg',...extra});
const build=records=>progress.build(records,lookup,{through:'2026-10-10'});
let results=build({'2026-10-01':[lift(16)],'2026-10-02':[lift(20)]});
assert.equal(results.bonusXP,50);assert.equal(results.achievements[0].records[0].previous,16);assert.equal(results.achievements[0].records[0].value,20);
let stats=progress.stats(results.groups[0].series.weight,'weight');assert.equal(stats.first.value,16);assert.equal(stats.previous.value,16);assert.equal(stats.latest.value,20);assert.equal(stats.best.value,20);
results=build({'2026-10-01':[lift(16)],'2026-10-02':[lift(20)],'2026-10-03':[lift(20)]});
assert.equal(results.bonusXP,50);stats=progress.stats(results.groups[0].series.weight,'weight');assert.equal(stats.lastDifferent.value,16);assert.equal(stats.previous.value,20);assert.equal(stats.latest.isRecord,false);
results=build({'2026-10-01':[lift(16)],'2026-10-02':[lift(20)],'2026-10-03':[lift(18)]});assert.equal(results.bonusXP,50);assert.equal(progress.stats(results.groups[0].series.weight,'weight').best.value,20);
results=build({'2026-10-01':[lift(16)],'2026-10-02':[lift(20,{reps:12})]});assert.equal(results.achievements.length,1);assert.equal(results.achievements[0].records.length,2);assert.equal(results.bonusXP,50);
assert.equal(build({'2026-10-01':[lift(16)],'2026-10-02':[lift(20,{done:false})],'2026-10-11':[lift(30)]}).bonusXP,0);
assert.equal(build({'2026-10-01':[lift(16)],'2026-10-02':[lift(-2)]}).groups[0].series.weight.length,1);
assert.equal(build({'2026-10-01':[lift(16)],'2026-10-02':[lift(16/progress.KG_PER_LB,{weightUnit:'lb'})]}).bonusXP,0);
assert.equal(build({'2026-09-30':[lift(30)],'2026-10-01':[lift(16)],'2026-10-02':[lift(20)]}).bonusXP,0);
assert.equal(build({'2026-10-01':[lift(16)]}).bonusXP,0);
const run=(id,distance,minutes,extra={})=>({id,name:'Running',done:true,tracking:'time',minutes,distance:{value:distance,unit:'km'},...extra});
results=build({'2026-10-01':[run('a',5,30,{source:'Garmin Connect'})],'2026-10-02':[run('b',5,25,{name:'  RUNNING ',source:'Apple Fitness'})]});
assert.equal(results.groups.length,1);assert.equal(results.groups[0].series.speed[0].value,10);assert.equal(results.groups[0].series.speed[1].value,12);assert.equal(results.achievements[0].records[0].metric,'speed');assert.equal(results.bonusXP,50);
assert.equal(build({'2026-10-01':[run('a',5,30)],'2026-10-02':[run('b',5/progress.KM_PER_MI,30,{distance:{value:5/progress.KM_PER_MI,unit:'mi'}})]}).bonusXP,0);
assert.equal(progress.distanceKm({value:5000,unit:'m'}),5);assert.equal(progress.distanceKm({value:1,unit:'invalid'}),null);
assert.equal(progress.values(run('a',5,0)).speed,undefined);assert.equal(progress.values(run('a',0,30)).speed,undefined);assert.equal(progress.values(run('a',5,-30)).speed,undefined);
results=build({'2026-10-01':[lift(40,{id:'assisted',weightKind:'assistance'})],'2026-10-02':[lift(30,{id:'assisted',weightKind:'assistance'})],'2026-10-03':[lift(0,{id:'assisted',weightKind:'assistance'})]});
assert.equal(results.bonusXP,100);assert.equal(progress.stats(results.groups[0].series.assistance,'assistance').best.value,0);
results=build({'2026-10-01':[lift(16),lift(24,{id:'other'})],'2026-10-02':[lift(20)]});assert.equal(results.groups.length,2);assert.equal(results.bonusXP,50);
results=build({'2026-10-01':[lift(16)],'2026-10-02':[{id:'import-1',name:'Dumbbell Curl',done:true,weight:20,weightUnit:'kg',tracking:'reps'}]});assert.equal(results.groups.length,1);assert.equal(results.bonusXP,50);
results=build({'2026-10-01':[run('later',5,25,{time:'12:00'}),run('earlier',5,30,{time:'09:00'})]});assert.equal(results.groups[0].series.speed[0].id,'earlier');assert.equal(results.bonusXP,50);
console.log('PASS: baseline/previous/last-different/best comparisons, true records, one bonus per session, ties, units, speed, assistance, activity grouping, backfills, edits and ordering.');
