const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const sandbox={};sandbox.window=sandbox;vm.createContext(sandbox);
for(const file of ['workout-tracking.js','progress-data.js'])vm.runInContext(fs.readFileSync('dist/'+file,'utf8'),sandbox);
const progress=sandbox.GymProgressData;
const catalog={curl:{id:'curl',name:'Dumbbell Curl',group:'Biceps'},other:{id:'other',name:'Hammer Curl',group:'Biceps'},assisted:{id:'assisted',name:'Machine Assisted Pull-Up',equipment:'Machine',group:'Back'}};
const lookup=record=>catalog[record.id]||{id:record.id,name:record.name,group:record.group||'Activity'};
const lift=(weight,extra={})=>({id:'curl',done:true,tracking:'reps',sets:3,reps:10,weight,weightUnit:'kg',...extra});
const build=records=>progress.build(records,lookup,{through:'2026-10-10'});
let results=build({'2026-10-01':[lift(16)],'2026-10-02':[lift(20)]});
assert.equal(results.bonusXP,50);assert.equal(results.achievements[0].records[0].previous,16);assert.equal(results.achievements[0].records[0].value,20);
let stats=progress.stats(results.groups[0].series.weight,'weight');assert.equal(stats.first.value,16);assert.equal(stats.previous.value,16);assert.equal(stats.latest.value,20);assert.equal(stats.best.value,20);
results=build({'2026-10-01':[lift(16)],'2026-10-02':[lift(20)],'2026-10-03':[lift(20)]});
assert.equal(results.bonusXP,50);stats=progress.stats(results.groups[0].series.weight,'weight');assert.equal(stats.lastDifferent.value,16);assert.equal(stats.previous.value,20);assert.equal(stats.latest.isRecord,false);
results=build({'2026-10-01':[lift(16)],'2026-10-02':[lift(20)],'2026-10-03':[lift(18)]});assert.equal(results.bonusXP,50);assert.equal(progress.stats(results.groups[0].series.weight,'weight').best.value,20);
results=build({'2026-10-01':[lift(16)],'2026-10-02':[lift(20,{reps:12})]});assert.equal(results.achievements.length,1);assert.equal(results.achievements[0].records.length,2);assert.equal(results.bonusXP,50);
assert.equal(build({'2026-10-01':[lift(16)],'2026-10-02':[lift(20,{done:false})],'2026-10-11':[lift(30)]}).bonusXP,0);
assert.equal(build({'2026-10-01':[lift(16)],'2026-10-02':[lift(-2)]}).groups[0].series.weight.length,1);
assert.equal(build({'2026-10-01':[lift(16)],'2026-10-02':[lift(16/progress.KG_PER_LB,{weightUnit:'lb'})]}).bonusXP,0);
assert.equal(build({'2026-09-30':[lift(30)],'2026-10-01':[lift(16)],'2026-10-02':[lift(20)]}).bonusXP,0);
assert.equal(build({'2026-10-01':[lift(16)]}).bonusXP,0);
const run=(id,distance,minutes,extra={})=>({id,name:'Running',done:true,tracking:'time',minutes,distance:{value:distance,unit:'km'},...extra});
results=build({'2026-10-01':[run('a',5,30,{source:'Garmin Connect'})],'2026-10-02':[run('b',5,25,{name:'  RUNNING ',source:'Apple Fitness'})]});
assert.equal(results.groups.length,1);assert.equal(results.groups[0].series.speed[0].value,10);assert.equal(results.groups[0].series.speed[1].value,12);assert.equal(results.achievements[0].records[0].metric,'speed');assert.equal(results.bonusXP,50);
assert.equal(build({'2026-10-01':[run('a',5,30)],'2026-10-02':[run('b',5/progress.KM_PER_MI,30,{distance:{value:5/progress.KM_PER_MI,unit:'mi'}})]}).bonusXP,0);
assert.equal(progress.distanceKm({value:5000,unit:'m'}),5);assert.equal(progress.distanceKm({value:1,unit:'invalid'}),null);
assert.equal(progress.values(run('a',5,0)).speed,undefined);assert.equal(progress.values(run('a',0,30)).speed,undefined);assert.equal(progress.values(run('a',5,-30)).speed,undefined);
results=build({'2026-10-01':[lift(40,{id:'assisted',weightKind:'assistance'})],'2026-10-02':[lift(30,{id:'assisted',weightKind:'assistance'})],'2026-10-03':[lift(0,{id:'assisted',weightKind:'assistance'})]});
assert.equal(results.bonusXP,100);assert.equal(progress.stats(results.groups[0].series.assistance,'assistance').best.value,0);
results=build({'2026-10-01':[lift(16),lift(24,{id:'other'})],'2026-10-02':[lift(20)]});assert.equal(results.groups.length,2);assert.equal(results.bonusXP,50);
results=build({'2026-10-01':[lift(16)],'2026-10-02':[{id:'import-1',name:'Dumbbell Curl',done:true,weight:20,weightUnit:'kg',tracking:'reps'}]});assert.equal(results.groups.length,1);assert.equal(results.bonusXP,50);
results=build({'2026-10-01':[run('later',5,25,{time:'12:00'}),run('earlier',5,30,{time:'09:00'})]});assert.equal(results.groups[0].series.speed[0].id,'earlier');assert.equal(results.bonusXP,50);
const batches=[{sets:1,reps:1,weight:20,weightUnit:'kg'},{sets:1,reps:1,weight:10,weightUnit:'kg'},{sets:5,reps:10,weight:5,weightUnit:'kg'}];
const multiple=lift(999,{sets:999,reps:999,setEntries:batches});
assert.equal(sandbox.GymTracking.totals(multiple).sets,7);assert.equal(sandbox.GymTracking.totals(multiple).reps,52);
assert.equal(progress.values(multiple,catalog.curl).weight,20);assert.equal(progress.values(multiple,catalog.curl).reps,52);
results=build({'2026-10-01':[lift(16)],'2026-10-02':[multiple]});assert.equal(results.bonusXP,50);assert.equal(results.achievements[0].records.length,2);
assert.equal(results.groups[0].series.weight[1].totalSets,7);assert.equal(results.groups[0].series.weight[1].totalReps,52);
const mixed=lift(999,{setEntries:[...batches,{sets:1,reps:3,weight:50,weightUnit:'lb'},{sets:null,reps:null,weight:500,weightUnit:'kg'}]});
assert.equal(progress.values(mixed,catalog.curl).weight,50*progress.KG_PER_LB);assert.equal(progress.values(mixed,catalog.curl).reps,55);
results=build({'2026-10-01':[lift(16)],'2026-10-02':[mixed]});assert.equal(results.groups[0].series.weight[1].weightUnit,'lb');assert.equal(results.bonusXP,50);
assert.equal(progress.values(lift(999,{setEntries:[]}),catalog.curl).weight,undefined);assert.equal(progress.values(lift(999,{setEntries:[]}),catalog.curl).reps,undefined);
assert.equal(progress.values(lift(999,{setEntries:[null,{sets:-1,reps:10,weight:1000},{sets:1.5,reps:10,weight:1000}]}),catalog.curl).weight,undefined);
const aggregate=lift(1,{setEntries:[{sets:1000,reps:1000,weight:1},{sets:1000,reps:1000,weight:1}]});assert.equal(progress.values(aggregate,catalog.curl).reps,2000000);
assert.equal(sandbox.GymTracking.totals(aggregate).sets,2000);
const assistedBatches=lift(100,{id:'assisted',weightKind:'assistance',setEntries:[{sets:2,reps:8,weight:40,weightUnit:'kg'},{sets:1,reps:5,weight:0,weightUnit:'kg'}]});assert.equal(progress.values(assistedBatches,catalog.assisted).assistance,0);
const copy=structuredClone(multiple);sandbox.GymTracking.removeEntry(copy,0);assert.equal(copy.weight,10);assert.equal(progress.values(copy,catalog.curl).weight,10);assert.equal(progress.values(copy,catalog.curl).reps,51);
sandbox.GymTracking.addEntry(copy,'lb');assert.equal(copy.setEntries.at(-1).sets,null);assert.equal(copy.setEntries.at(-1).weightUnit,'lb');assert.equal(progress.values(copy,catalog.curl).reps,51);
sandbox.GymTracking.writeEntry(copy,0,'reps',4);assert.equal(copy.reps,4);assert.equal(progress.values(copy,catalog.curl).reps,54);
copy.tracking='time';copy.minutes=5;assert.equal(progress.values(copy,catalog.curl).weight,10);assert.equal(progress.values(copy,catalog.curl).reps,undefined);copy.tracking='reps';assert.equal(progress.values(copy,catalog.curl).reps,54);
assert.equal(sandbox.GymTracking.strength([multiple,{...multiple,done:false}],lookup).reps,52);
const legacyLoad={sets:1,reps:1,weight:16};sandbox.GymTracking.addEntry(legacyLoad,'lb');assert.equal(legacyLoad.setEntries[0].weightUnit,'kg');assert.equal(legacyLoad.setEntries[1].weightUnit,'lb');assert.equal(sandbox.GymTracking.measuredLoad(legacyLoad,catalog.curl).kg,16);
console.log('PASS: baseline/previous/last-different/best comparisons, true records, one bonus per session, ties, units, speed, assistance, activity grouping, backfills, edits and ordering.');
